# Maps of concept to terms.
outcome_mapping = {
    "offspring": {
        "obesity/overweight/bmi": [
            "obes",
            "weight status",
            "rate of weight change",
            "weight trajectory",
            "excess weight",
            "overweight",
            "body mass index",
            "bmi",
            "^(?!.*fetal)(?!.*foetal).*growth(?! restriction)",
            "adipos",
            "waist",
            "fat",
            "circumference",
        ],
        "height": [
            "stunting",
            "length trajectory",
        ],
        "asthma": ["asthma"],
        "microbiome/mycobiome/virome": [
            "microbiome",
            "microbiota",
            "mycobiome",
            "virome",
            "bifidobacterium",
            "lactobacillus",
            "gut bacteria",
            "gut microb",
            "infant gut",
            "gastrointestinal tract colonization",
            "microbial community richness",
            "gut colon",
            "yeast",
            "oral bacterial colonization",
            "urobiome",
            "abundance",
        ],
        "allergy/atopy": [
            "allerg",
            "atop",
            "sensitization",
            "sensitisation",
            "multiple chemical sensitivity",
            "cmpa",
        ],
        "eczema": ["eczema"],
        "autism": ["autis", "asperger"],
        "cognitive development": [
            "developmental delay",
            "cognitive",
            "school performance",
            "school achievement",
            "reading proficiency",
            "intelligence",
            "intellect",
            "learning disabilit",
            r"\biq\b",
            "education",
            "neurodevelopment",
            "neuropsychological",
            "motor skill",
            "motor development",
            "academic",
            "mental development",
            "infant motor scale",
            "developmental",
            "slow learning",
        ],
        "cancer": [
            "cancer",
            "neoplas",
            "leuka?emia",
            "tumour",
            "tumor",
            "lymphoma",
            "blastoma",
            "malignanc",
            "meningioma",
            "b-cell precursor all",
            "early.onset all",
            "rhabdomyosarcoma",
        ],
        "disability": ["disabilit"],
        "behaviour problems": ["behaviour", "behavior"],
        "learning disability": [
            "learning disabilit",
            "slow learning",
        ],
        "precocious puberty": [
            "pubert",
            "menarcheal age",
        ],
        "diabetes": [
            "(?<!gestational )(?<!non)(?<!non-)diabet",
            "^(?!.*neonat).*glucose",
            "islet autoimmun",
        ],
        "vaccine efficacy": ["vaccin"],
        "hypertension": [
            "^(?!.*pregnancy).*hypertension(?! in pregnancy)",
            "blood pressure",
        ],
        "cardiovascular risk": [
            "^(?!.*pregnancy).*hypertension(?! in pregnancy)",
            "blood pressure",
            "vascular risk",
            "cardiorespiratory",
        ],
        "metabolic dysregulation": [
            "metabolic syndrome",
            "lipid metabolism",
            "adiponectin",
            "insulin resistance",
        ],
        "child death": [
            "child death",
            "child mortality",
            "child survival",
            "under.?five mortality",
        ],
        "bowel disease": [
            "crohn",
            "irritable bowel",
            "ibd",
            "ulcerative colitis",
            "irritable bowel",
            "inflammatory bowel",
        ],
        "coeliac disease": ["celiac", "coeliac"],
        "ADHD": ["adhd", "attention", "impulsiv"],
        "laryngomalacia": ["laryngomalacia"],
        "multiple sclerosis": ["multiple sclerosis", "ms susceptibility"],
        "constipation": ["constipation"],
        "hip dysplasia": ["hip dysplasia", "dysplasia of the hip", "ddh"],
        "cataract": ["cataract"],
        "refractive disorder": [
            "myopia",
            "hypermetropia",
            "astigmatism",
            "refractive disorder",
            "visual impairment without correction",
        ],
        "urinary tract infection": [
            "urinary tract infect",
        ],
        "ear infection": [
            "otitis media",
        ],
        "gastrointestinal infection": ["gastroenteritis", "gastrointestinal infect"],
        "respiratory infection": [
            "respiratory (?:tract )?infect",
            "bronchiolitis",
            "pneumonia",
        ],
        "psychosis": ["psychosis", "psychotic"],
        "strabismus": ["strabismus"],
        "esophagitis": ["esophag"],
        "wheezing": ["wheezing"],
        "dental issues": [
            "caries",
            "dental",
            "mutans",
            "cariogenic",
            "hypominerali[sz]ation",
            "teeth",
            "malocclusion",
        ],
        # "cerebral palsy": ["cerebral palsy"],
        "hospitalisation": [
            # "(?<!length of )(?<!duration of )hospitali[sz]ation(?! duration)(?! length)",
            r"^(?!.*neonatal)(?!.*duration)(?!.*length).*admission(?: \S+ ){0,5}hospital",
            r"^(?!.*duration)(?!.*length)(?: \S+ ){0,5}hospital.*admission",
            "hospitali[sz]ation",
            "(?>!neonatal )in.?patient",
            "hospital stays",
        ],
        "epilepsy": ["epilepsy"],
        "hearing loss": ["hearing loss"],
        "epigenetics": ["epigenetic", "methylation"],
        "sleep apnoea": ["sleep"],
        "nasolacrimal duct issues": [
            "dacryocystitis",
            "cnldo",
            "nasolacrimal duct obstruction",
            "dacryoscintigraphy",
        ],
        "hematologic morbidity": ["ha?ematologic"],
        "iron status": [
            "iron",
            "ferritin",
            "ana?emia",
        ],
        "tic disorders": [r"\btic disorder"],
        "eating disorders": ["anorexia"],
        "mood disorders": [
            "mood disorder",
            "depression",
            "bipolar",
            "affective disorder",
        ],
        "kawasaki disease": ["kawasaki"],
        "anxiety disorders": [
            "anxiety",
            "stress-related disorder",
            "obsessive-compulsive disorder",
        ],
        "self-harm": ["self.harm"],
        "thyroid hormone levels": [
            r"^(?!.*cord blood).*\btsh\b",
            "t^(?!.*cord blood).*hyroid.stimulating hormone",
            "hypothyroidism",
        ],
        "ankylosing spondylitis": ["ankylosing spondylitis"],
        "undescended testes": ["undescended test"],
        "brain parameters": ["gray matter volume", "brain development"],
        "intestinal permeability": ["zonulin"],
        "schizophrenia": ["scz-d"],
        "immune system status": [
            "cytokine",
        ],
        "sensory issues": ["sensory"],
        "semen quality": ["semen"],
        "neuromyelitis optica": ["neuromyelitis optica"],
        # "cost of illness": ["cost"],
        "requiring surgery using general anaesthesia": ["general anesthesia"],
        "abdominal pain": ["abdominal pain"],
        "red blood cell parameters": [
            "red blood cell parameters",
            # "ha?emoglobin",
            "erythrocyte",
            # "hematocrit",
        ],
        "febrile seizures": ["febrile seizure"],
        "systemic lupus erythematosus": ["sle incidence"],
        "mandibular asymmetry": ["mandibular asymmetry"],
        "septal deviation": ["septal deviation"],
    },
    "women": {
        "urinary incontinence": [
            "urinary incontinence",
            "bladder(?! injur)(?! lesion)",
            "double incontinence",
            "postpartum incontinence",
            r"\bluts\b",
        ],
        "faecal incontinence": [
            "faecal incontinence",
            "fecal incontinence",
            "double incontinence",
            "anal incont",
        ],
        "constipation": ["constipation"],
        "nocturia": ["nocturia"],
        "pelvic floor": [
            "pelvic floor",
            "manometry",
            "sphincter pressure",
            "vaginal support",
            "vaginal angle",
        ],
        "prolapse": [
            "prolapse",
            "recto.?vaginal septum",
            "rectocele",
            "anal canal anatomy",
            r"\bpop\b",
            "cystocele",
        ],
        "sexual dysfunction": [
            "sexual",
            "sex life",
        ],
        "quality of life/self-rated health": [
            "quality of life",
            "qol",
            "self-rated health",
        ],
        "anaemia": [
            "ana?emia",
        ],
        "birth experience": [
            "birth experience",
            "birth satisfaction",
        ],
        "chronic pain": [
            "pain(?! relief)",
            "dyspareunia",
            "dysmenorrhea",
            "period pain",
        ],
        "fistula": ["fistula"],
        "endometriosis": ["endometriosis"],
        "mood disorders": [
            "ppd",
            "depression",
            "mood disorder",
            "psychotropic medication",
            "anti.?depressant",
        ],
        "anxiety disorders": ["anxiety"],
        "PTSD": [
            "ptsd",
            "post.?traumatic stress",
        ],
        "menstrual issues": ["menstrua", "dysmenorrhea", "period pain"],
        "cancer": ["cancer", "cervical dysplasia", "neoplas"],
        "new opioid use": ["opioid use"],
        # "later hysterectomy complications": [
        #     "vaginal hysterectomy",
        #     "robotic hysterectomy",
        #     "laparoscopic hysterectomy",
        #     "within 30 days of hysterectomy",
        #     "clavien-dindo",
        #     "uterine debulking",
        #     "complications during subsequent hysterectomy",
        #     "conversion to laparotomy",
        # ],
        # "contraceptive use": ["contracept"],
        "diastasis recti": ["diastasis recti"],
        # "IUD issues": [
        #     "intra.?uterine(?! growth)",
        #     r"\biucds?\b",
        # ],
        "adhesions": ["adhesion"],
        "small bowel obstruction": ["small bowel obstruction"],
        # "need for mid-urethral sling revision surgery": ["mid-urethral sling"],
        "sacroiliac joint issue": ["sacroiliac joint"],
        "hypertension": [
            "^(?!.*pregnancy).*hypertension(?! in pregnancy)",
        ],
        "BMI/postpartum weight loss": [
            "body mass index",
            "bmi",
            "weight retention",
        ],
        "systemic sclerosis": ["systemic sclerosis"],
        "coronary heart disease": ["coronary heart disease"],
        "adenomyosis": ["adenomyosis"],
        # "post-LEEP complications": ["post.leep"],
        # "uterine fibroid embolisation complications": [r"\bufe\b"],
        # "ability to perform salpingectomy at time of hysterectomy": [
        #     "obs at time of vh"
        # ],
        # "ability to use abdominal tissue for breast reconstruction": [
        #     r"\bdiep\b",
        #     "flap failure",
        # ],
        "metabolic syndrome": ["metabolic syndrome"],
        "vaginal laxity": ["vaginal laxity"],
        "parenting stress": ["parenting stress"],
        "postural control": ["postural control"],
        "abnormal uterine bleeding": [
            "abnormal uterine bleeding",
            "dysfunctional uterine bleeding",
        ],
        "hospitalisation": [
            # "(?<!length of )(?<!duration of )hospitali[sz]ation(?! duration)(?! length)",
            r"^(?!.*neonatal)(?!.*duration)(?!.*length).*admission(?: \S+ ){0,5}hospital",
            r"^(?!.*duration)(?!.*length)(?: \S+ ){0,5}hospital.*admission",
            "hospitali[sz]ation",
            "(?>!neonatal )in.?patient",
        ],
        "uterine microbiome": ["uterus microbial flora"],
        "vaginal microbiome": ["vaginal microbi"],
        # "athlete performance": ["physical function after childbirth"],
        "new-onset irritable bowel syndrome": ["irritable bowel syndrome"],
        "uterine niche": ["uterine niche"],
        "biliary cholangitis": ["biliary cholangitis"],
        "degenerative spondylolisthesis": ["spondylolisthesis"],
        # "ovarian reserve": ["ovarian morphometry"],
        # "colonoscopy complications": [
        #     "bowel preparation quality",
        #     "cecal intubation time",
        # ],
        # "sex worker chlamydia infection": ["chlamydia"],
        # "missed miscarriage": ["missed abortion"],
        # "increased fear of childbirth": ["childbirth fear"],
        # "termination of preganancy issues": [
        #     "fo?etal expulsion",
        #     "uterine evacuation",
        # ],
        "spinal issues": ["lumbar disc", "lumbar spin"],
        "abdominal muscle thickness": ["abdominal muscle thickness"],
        "adenomyosis": ["adenomyosis", "TGF-β1 expression in endometri"],
        "venous thromboembolism": ["venous thromboembolism"],
        "pulmonary embolism": ["pulmonary embolism"],
        "suicide": ["suicide"],
        "cervical elasticity": ["elastography"],
        "hernia": ["hernia"],
        "interstitial cystitis": ["interstitial cystitis"],
    },
    "dyad": {
        "breastfeeding": [
            "breast.?feeding(?! initiation)",
            "breast.?fed",
            "bottle.?feeding",
            "formula",
        ],
        "bonding": ["bond"],
    },
    "societal": {
        "antimicrobial resistance": ["resistome", "antibiotic resistance", r"\besbl\b"],
    },
}
outcome_mapping["offspring"]["autoimmune disorders"] = [
    "autoimmune",
    "immune-mediated inflammatory",
]
outcome_mapping["offspring"]["psychiatric disorders"] = ["psychiatric"] + (
    outcome_mapping["offspring"]["mood disorders"]
    + outcome_mapping["offspring"]["eating disorders"]
    + outcome_mapping["offspring"]["anxiety disorders"]
    + outcome_mapping["offspring"]["self-harm"]
    + outcome_mapping["offspring"]["schizophrenia"]
    + outcome_mapping["offspring"]["ADHD"]
)
outcome_mapping["offspring"]["infection"] = [
    "infection burden",
    "infection-related hospitalisation",
    "hospitalization with infection",
    "risk of infection",
    "cost of illness",  # Specific phrase for a study examining health system costs of childhood illness
] + (
    outcome_mapping["offspring"]["urinary tract infection"]
    + outcome_mapping["offspring"]["ear infection"]
    + outcome_mapping["offspring"]["gastrointestinal infection"]
    + outcome_mapping["offspring"]["respiratory infection"]
)
outcome_mapping["women"]["psychiatric disorders"] = ["psychiatric"] + (
    outcome_mapping["women"]["mood disorders"]
    + outcome_mapping["women"]["anxiety disorders"]
    + outcome_mapping["women"]["PTSD"]
)
outcome_mapping["women"]["pelvic floor related issues"] = (
    outcome_mapping["women"]["urinary incontinence"]
    + outcome_mapping["women"]["faecal incontinence"]
    + outcome_mapping["women"]["prolapse"]
    + outcome_mapping["women"]["pelvic floor"]
)

